# ===================================
# BASE DE DATOS ORACLE
# ===================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=empleados_user
spring.datasource.password=Empleados123

# ===================================
# JPA / HIBERNATE
# ===================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true